/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dnddiceapp;
import java.awt.*; 
import javax.swing.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    private static void printWindow() {
        JFrame window = new JFrame("First Window");
        JLabel text = new JLabel("WOW! A Label!", SwingConstants.CENTER);
        text.setPreferredSize(new Dimension(300, 100));
        window.getContentPane().add(text, BorderLayout.CENTER);
        window.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        window.setLocationRelativeTo(null);
        window.pack();
        window.setVisible(true);
    }
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        printWindow();
    }
}

