/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dnddiceapp;
import java.awt.*;
import javax.swing.*;
import javax.swing.text.*;

public class App {
    private static void printWindow() {
        JFrame window = new JFrame("DND Dice App");
        JPanel panel = new JPanel();
        GroupLayout layout = new GroupLayout(panel);
        JButton roll = new JButton("ROLL");
        JButton clear = new JButton("CLEAR");
        JTextField input = new JTextField();
        input.setColumns(40);
        input.setFont(new Font(input.getFont().getName(), Font.PLAIN, 20));
        JTextPane recentRoll = new JTextPane();
        recentRoll.setEditable(false);
        recentRoll.setText("First Line\nTEST");
        recentRoll.setMinimumSize(new Dimension(50, 500));
        SimpleAttributeSet attrs = new SimpleAttributeSet();
        StyleConstants.setAlignment(attrs,StyleConstants.ALIGN_CENTER);
        recentRoll.setParagraphAttributes( attrs, false);
        // recentRoll.setRows(10);
        recentRoll.setFont(new Font(recentRoll.getFont().getName(), Font.PLAIN, 40));
        JTextPane pastRolls = new JTextPane();
        pastRolls.setEditable(false);
        pastRolls.setMinimumSize(new Dimension(50, 500));
        pastRolls.setText("TEST");

        // pastRolls.setRows(10);

        roll.setMinimumSize(new Dimension(recentRoll.getWidth(), roll.getHeight()));
        layout.setAutoCreateGaps(true);
        layout.setAutoCreateContainerGaps(true);
        layout.setVerticalGroup(layout.createSequentialGroup()
            .addComponent(input)
            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(recentRoll)
                .addComponent(pastRolls))
            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(roll)
                .addComponent(clear)
            )
        );
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(input)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(recentRoll)
                        .addComponent(roll))
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(pastRolls)
                        .addComponent(clear)))
        );
        panel.setLayout(layout);

        window.getContentPane().add(panel, BorderLayout.CENTER);
        window.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        window.pack();
        window.setLocationRelativeTo(null);
        window.setResizable(false);
        window.setVisible(true);
    }
    public static void main(String[] args) {
        printWindow();
    }

}

